### ISSUE TITLE
TICK numerical variable definition

### ISSUE THREAD

**Issue by miili** [influxdb/kapacitor#107]
Defining variables in TICK works for objects but numerical variables, useful for eg. thresholds, do not work.

Is there a plan to implement file global definitions of numerical variables?

**Comment by nathanielc** [comment]
So something like this?

```
var cpuThreshold = 10.0

stream.from().
   .alert()
       .crit(lambda: "value" > cpuThreshold)

```

Yes, I plan to support this kind of behavior.
