### ISSUE TITLE
Multiple subscriptions per alert

### ISSUE THREAD

**Issue by panda87** [influxdb/kapacitor#116]
It would be nice if we will be able to use more than one subscribers \ service.
For example, Slack + email

Thanks

**Comment by nathanielc** [comment]
This is currently possible:

```
.alert()
   .warn(...)
   .cirt(...)
   .email('oncall@example.com')
   .slack()
      .channel('#alets')
```

**Comment by panda87** [comment]
ohhh Thanks @nathanielc
