### ISSUE TITLE
[Feature] - Alert to HipChat

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/kapacitor#119]
Hi team,

Will be great if we could push alert to an hipchat room.
Do you think it's possible ?

Thanks,
Julien.

**Comment by nathanielc** [comment]
This should be easy to add. Do you want to take a crack at it? Just follow the code for Slack.

Contributing the handler is pretty straight forward:

1. Create a new service in the services package and implement methods for interacting with HipChat.
2. Add the HipChat service to the cmd/kapacitord/run package so the server can open/close and configure the service.
3. Update the AlertNode in pipeline so the TICKscripts can declare HipChat options
4. Update the AlertNode in kapacitor to register the handler when configured via the TICKscript.
5. Update the TaskMaster to have an interface for communicating with the HipChat service.
