### ISSUE TITLE
Difference between a task being enabled and a task executing

### ISSUE THREAD

**Issue by rossmcdonald** [influxdb/kapacitor#123]
Using:

```
root@kapacitor1:/tmp# kapacitor version
Kapacitor 0.2.3 (git: master 7ea4a548108e82a214d6c7a94b66a59ffeda1bd9)
```

What does it mean for a task to be enabled, but not executing? For example:

```
root@kapacitor1:/tmp# kapacitor list tasks
Name                          Type      Enabled   Executing Databases and Retention Policies
disk_alert                    stream    true      false     ["telegraf"."default"]
```

Where `Enabled` is set to `true`, but `Executing` is set to `false`. When this happens, redefining and/or re-enabling doesn't seem to help. Deleting the task and re-adding does work, though. I've also been re-adding and modifying the tickscript fairly often, so I'm not sure if that could have an effect. There also doesn't seem to be anything logged when this occurs.

So my questions are:

* Is this expected?
* Is this a symptom of an error in the tickscript or tickscript's execution?
* Is there a way to 're-execute' a task?

**Comment by nathanielc** [comment]
If a TICKscript is not valid etc you will get an error when you try to enable the task and will be able to fix it at that point. But it is possible to right a TICKscript that is valid syntactically but could have an error based on the data the task is given(i.e. you could reference a field name that doesn't exist). If you get an that is data dependent the task will stop `executing`.

When a task is enabled but it is not executing it means it had an error and has therefore stopped executing. Using `kapacitor show disk_alert` you can get more information on the state of the task and why it is not executing. 

Running `kapacitor reload disk_alert` should `re-execute` the task but if its getting an error when the task first starts running then it will quickly change to `Executing: false` state again.

**Comment by rossmcdonald** [comment]
Thanks for the explanation @nathanielc! It ended up being a type issue in one of my lambda expressions. I also had debug logging on, so I missed the error message.

Thanks again!
