### ISSUE TITLE
Subscriptions causing problems with inflluxdb 0.9.4.2

### ISSUE THREAD

**Issue by jlark** [influxdb/kapacitor#74]
Hello,
I was setting up Kapacitor to play with some alerting though I've run into a problem right around the getgo.
I'm running inflxdb 0.9.4.
When I start Kapacitor I get 
2015/12/02 13:14:51 Using configuration at: kapacitor.conf
run: open server: open service: error parsing query: found SUBSCRIPTIONS, expected CONTINUOUS, DATABASES, FIELD, GRANTS, MEASUREMENTS, RETENTION, SERIES, SERVERS, TAG, USERS at line 1, char 6

Looking at the documentation https://github.com/influxdb/influxdb/blob/0.9.5/influxql/INFLUXQL.md

I've tried a few subscription queries and I also get the same error. So this might belong as an error on the influxdb side. Apologies if that's the case. I was able to create continuous queries without problem though.

Oddly I don't see any mention of SUBSCRIPTIONS in this documentation https://influxdb.com/docs/v0.9/query_language/continuous_queries.html

So I'm not sure where the exact problem is. Influxdb or kapacitor.

Thanks!
Alp

**Comment by nathanielc** [comment]
Subscriptions was added in influxdb 0.9.5 you will need to upgrade. That
should fix the issue.

**Comment by jlark** [comment]
Interesting I downloaded the latest off the site just toda but looks like I didn't restart the service.
I was getting this.
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.4.2
InfluxDB shell 0.9.5.1

Now:
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1

Looks like this is working now.
Thanks,
Alp
