### ISSUE TITLE
Alert reloads not working

### ISSUE THREAD

**Issue by jlark** [influxdb/kapacitor#81]
Hi,
I'm trying to reload my alerts and it doesn't seem to be working. 

Please see sequence below.
dev@sesh-dev1:~/alerts$ kapacitor show test_alert
Name: test_alert
Error:
Type: stream
Enabled: true
Databases Retention Policies: ["sesh"."default"]
TICKscript:
stream
    // Select just the cpu_usage_idle measurement from our example database.
    .from().measurement('DCVolt1')
    .alert()
        .crit(lambda: "value" < 30 )
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

DOT:
digraph test_alert {
stream0 -> stream1;
stream1 -> alert2;
}

dev@sesh-dev1:~/alerts$ cat test_alert.tick
stream
    // Select just the cpu_usage_idle measurement from our example database.
    .from().measurement('DCVolt1')
        .as("Battery_Voltage")
    .alert()
        .crit(lambda: "value" < 30 )
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')
        .slack() //added slack
        .email() //added email

dev@sesh-dev1:~/alerts$ kapacitor reload test_alert

dev@sesh-dev1:~/alerts$ kapacitor show test_alert
Name: test_alert
Error:
Type: stream
Enabled: true
Databases Retention Policies: ["sesh"."default"]
TICKscript:
stream
    // Select just the cpu_usage_idle measurement from our example database.
    .from().measurement('DCVolt1')
    .alert()
        .crit(lambda: "value" < 30 )
        // Whenever we get an alert write it to a file.
        .log('/tmp/alerts.log')

DOT:
digraph test_alert {
stream0 -> stream1;
stream1 -> alert2;
}

Nothing in the logs indicating an error.

**Comment by nathanielc** [comment]
Try defining before the reload

kapacitor define -name test_alert -tick test_alert.tick

Hi,
I'm trying to reload my alerts and it doesn't seem to be working.

Please see sequence below.
dev@sesh-dev1:~/alerts$ kapacitor show test_alert
Name: test_alert
Error:
Type: stream
Enabled: true
Databases Retention Policies: ["sesh"."default"]
TICKscript:
stream
// Select just the cpu_usage_idle measurement from our example database.
.from().measurement('DCVolt1')
.alert()
.crit(lambda: "value" < 30 )
// Whenever we get an alert write it to a file.
.log('/tmp/alerts.log')

DOT:
digraph test_alert {
stream0 -> stream1;
stream1 -> alert2;
}
------------------------------
My modified alert

dev@sesh-dev1:~/alerts$ cat test_alert.tick
stream
// Select just the cpu_usage_idle measurement from our example database.
.from().measurement('DCVolt1')
.as("Battery_Voltage")
.alert()
.crit(lambda: "value" < 30 )
// Whenever we get an alert write it to a file.
.log('/tmp/alerts.log')
.slack() //added slack
.email() //added email

dev@sesh-dev1:~/alerts$ kapacitor reload test_alert

dev@sesh-dev1:~/alerts$ kapacitor show test_alert
Name: test_alert
Error:
Type: stream
Enabled: true
Databases Retention Policies: ["sesh"."default"]
TICKscript:
stream
// Select just the cpu_usage_idle measurement from our example database.
.from().measurement('DCVolt1')
.alert()
.crit(lambda: "value" < 30 )
// Whenever we get an alert write it to a file.
.log('/tmp/alerts.log')

DOT:
digraph test_alert {
stream0 -> stream1;
stream1 -> alert2;
}

Nothing in the logs indicating an error.

—
Reply to this email directly or view it on GitHub
<https://github.com/influxdb/kapacitor/issues/81>.

**Comment by jlark** [comment]
Hi,
 I already have the task defined.

Are you suggest I re-define it?

**Comment by jlark** [comment]
OK, When I redefined the task and then reloaded it got updated.

We should update the docs accordingly.

**Comment by jlark** [comment]
Hello,
I just upgraded to v0.2
Trying to reload simply hangs now.

**Comment by nathanielc** [comment]
@jlark I just discovered #86 A restart will fix clear the deadlock, obviously not ideal. I am working on fix now.

**Comment by jlark** [comment]
ok, so simply restart Kapacitord.

I'll give it a shot.

thnks,

**Comment by nathanielc** [comment]
@jackzampolin #86 has been fixed and a bug fix release was created 0.2.1
