### ISSUE TITLE
Kapacitor / Bosun

### ISSUE THREAD

**Issue by politician** [influxdb/kapacitor#84]
As a long-time InfluxDB customer, I'm hopeful about the futures of these new tools -- Telegraf, Chronograf, Kapacitor.  How does the vision / capabilities for Kapacitor differ from Bosun which is another alerting daemon from Stack Exchange?  What other alerting daemons are influencing the design of Kapacitor?

**Comment by nathanielc** [comment]
Kapacitor's vision is much broader than just an alerting framework. Kapacitor's goal is to be able to provide rich ways of detecting and triggering events from the data it is processing but then leaving the heavy lifting of managing the alert workflow (acknowledge, comment escalate, etc.) on third party tools like VictorOps and PagerDuty. 

As for other tools out there almost all of them have influenced Kapacitor in some way, Apache Storm, Flink, Spark, Riemann, and Bosun to just name a few.

**Comment by politician** [comment]
Thanks for the insight.
