### ISSUE TITLE
Bug: "kapacitor delete <task>" is not working

### ISSUE THREAD

**Issue by cloud-rocket** [influxdb/kapacitor#88]
I think it is somehow mapped to "enable" instead of "delete" because it throws 

```
vagrant@vagrant-ubuntu-trusty-64:~$ kapacitor delete event
Must pass at least one task name or recording ID
Usage: kapacitor enable [task name...]

        Enable and start a task running from the live data.

```

Kapacitor 0.2.0 (git: master 18b2061efb263aae326f51bd74d7023a221996ef)

**Comment by nathanielc** [comment]
The usage is `kapacitor delete tasks event` I'll fix the broken help message. Thanks for reporting.

**Comment by cloud-rocket** [comment]
tanx - it was not clear.....
Is the syntax somewhere documented (apart of command line help)?

**Comment by nathanielc** [comment]
No but `kapacitor help delete` does show the correct help message.
