### ISSUE TITLE
Kapacitor alerting on the whole batch

### ISSUE THREAD

**Issue by srini-raju** [influxdb/kapacitor#91]
I have 4 cpu's and telegraf sends 5 records each time it runs. I am trying the simple example for a stream against cpu_usage_idle with a value < 80. If any of the values in those 5 records is less than 80, its writing all 5 records to log instead of just the row that has value less than 80. See the output from log below. Only 3 rows have values below 80 but all 5 rows are in the alerts log.

{"id":"cpu_usage_idle:nil","message":"cpu_usage_idle:nil is CRITICAL","time":"2015-12-14T20:39:20Z","level":"CRITICAL","data":{"series":[{"name":"cpu_usage_idle","tags":{"cpu":"cpu0","host":"localhost"},"columns":["time","value"],"values":[["2015-12-14T20:39:20Z", **71.2**]]}]}}

{"id":"cpu_usage_idle:nil","message":"cpu_usage_idle:nil is OK","time":"2015-12-14T20:39:20Z","level":"OK","data":{"series":[{"name":"cpu_usage_idle","tags":{"cpu":"cpu1","host":"localhost"},"columns":["time","value"],"values":[["2015-12-14T20:39:20Z", **83.28328328328328**]]}]}}

{"id":"cpu_usage_idle:nil","message":"cpu_usage_idle:nil is CRITICAL","time":"2015-12-14T20:39:20Z","level":"CRITICAL","data":{"series":[{"name":"cpu_usage_idle","tags":{"cpu":"cpu2","host":"localhost"},"columns":["time","value"],"values":[["2015-12-14T20:39:20Z", **75.3**]]}]}}

{"id":"cpu_usage_idle:nil","message":"cpu_usage_idle:nil is OK","time":"2015-12-14T20:39:20Z","level":"OK","data":{"series":[{"name":"cpu_usage_idle","tags":{"cpu":"cpu3","host":"localhost"},"columns":["time","value"],"values":[["2015-12-14T20:39:20Z", **84.61538461538461**]]}]}}

{"id":"cpu_usage_idle:nil","message":"cpu_usage_idle:nil is CRITICAL","time":"2015-12-14T20:39:20Z","level":"CRITICAL","data":{"series":[{"name":"cpu_usage_idle","tags":{"cpu":"cpu-total","host":"localhost"},"columns":["time","value"],"values":[["2015-12-14T20:39:20Z", **78.6**]]}]}}

Alert:

Enabled: true
Databases Retention Policies: ["telegraf"."default"]
TICKscript:
stream
    .from().measurement('cpu_usage_idle')
    .alert()
        .crit(lambda: "value" <  80)
        .log('/tmp/alerts.log')

**Comment by nathanielc** [comment]
This is the expected behavior. Notice that the `level` property of the rows that are greater than 80 is `OK` not `CRITICAL`. Kapacitor will fire `recovery` events; meaning that the first time the value goes into an `OK` state from a non `OK` state it will trigger the event. Since the events are coming in 5 at a time from each core and some cores are below 80 while the others are above, the event state is bouncing between OK and CRITICAL. If you want the alert to treat each cpu separately then use a `groupBy` or filter the data for just the total cpu.

```
stream
.from().measurement('cpu_usage_idle')
.groupBy('cpu') // treat each cpu separately so they don't interfere with each other's states.
.alert()
.crit(lambda: "value" < 80)
.log('/tmp/alerts.log')
```
or 
```
stream
.from().measurement('cpu_usage_idle')
.where(lambda: "cpu" == 'cpu-total') //filter down the data to only look at total cpu.
.alert()
.crit(lambda: "value" < 80)
.log('/tmp/alerts.log')
```

**Comment by srini-raju** [comment]
Thanks @nathanielc . GroupBy helps but i still see the state changes. If within a group of 5 there is one critical record that row is alerted on with the level:critical correctly. The first record in the next batch shows in the log with level:ok. Looks like that is expected behavior. 

How do i filter those with level:ok, since they are of no use to me. Is there a reason why show them?

Thanks for the help.

**Comment by nathanielc** [comment]
The `OK` alerts are intended for use by alerting systems that need to know that the alert has recovered. There is currently no way to turn them off.

**Comment by srini-raju** [comment]
Thanks for the prompt response. Great project. Saved me a lot of time. Would be happy to contribute if needed.
