### ISSUE TITLE
Alert emitting to influxDB

### ISSUE THREAD

**Issue by miili** [influxdb/kapacitor#94]
Hi guys,

I want to push alerts into an dedicated influx table to display those in grafana/chronograf. Utilizing ```alert.exec()``` would work but wouldn't feel right.

What are your thoughts on integrating an ```alert.influx``` method to push alerts back into the database?

best,

M

**Comment by nathanielc** [comment]
I like the idea this is being discussed here #93

**Comment by nathanielc** [comment]
It is, #93 is still open. Please add examples etc of how you would like to see this work.
